# fly.toml app configuration file for AutoBebe Healthcare System Web Application
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autobebe-webapp'
primary_region = 'yyz'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024